//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billdetail
    {
        public int id { get; set; }
        public Nullable<int> bilid { get; set; }
        public Nullable<int> proid { get; set; }
        public Nullable<int> sizeid { get; set; }
        public Nullable<int> colorid { get; set; }
        public Nullable<int> quantity { get; set; }
        public string bilprice { get; set; }
        public string bilpricevnd { get; set; }
        public string bilmoney { get; set; }
        public Nullable<int> billlocation { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Bill_customers Bill_customers { get; set; }
    }
}
