//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiethinh
    {
        public int id { get; set; }
        public string IDsanpham { get; set; }
        public string Images { get; set; }
        public string Thumimg { get; set; }
        public string Thumsimg { get; set; }
        public Nullable<int> ord { get; set; }
    }
}
