//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentProduc
    {
        public int Id { get; set; }
        public Nullable<int> ProId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Point { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Active { get; set; }
        public string Level { get; set; }
    }
}
