//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public string Mail_Smtp { get; set; }
        public Nullable<short> Mail_Port { get; set; }
        public string Mail_Info { get; set; }
        public string Mail_Noreply { get; set; }
        public string Mail_Password { get; set; }
        public string PlaceHead { get; set; }
        public string PlaceBody { get; set; }
        public string GoogleId { get; set; }
        public string Contact { get; set; }
        public string DeliveryTerms { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<double> FreeShipping { get; set; }
        public string Copyright { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public string Lang { get; set; }
        public string Helpsize { get; set; }
        public Nullable<int> Location { get; set; }
        public string ToolScrip { get; set; }
        public string Icon { get; set; }
        public string Map { get; set; }
        public Nullable<int> pageging1 { get; set; }
        public Nullable<int> pageging2 { get; set; }
        public Nullable<int> pageging3 { get; set; }
        public Nullable<int> pageging4 { get; set; }
        public Nullable<int> pageging5 { get; set; }
    }
}
