//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Mail { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Active { get; set; }
        public string Lang { get; set; }
        public string NameEn { get; set; }
        public string CompanyEn { get; set; }
        public string AddressEn { get; set; }
        public string DetailEn { get; set; }
    }
}
