//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTdonhang
    {
        public int IdCTHD { get; set; }
        public Nullable<int> IDhd { get; set; }
        public string IDsanpham { get; set; }
        public string Tensanpham { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> Giaban { get; set; }
        public string Size { get; set; }
        public string Mausac { get; set; }
        public string Dungluong { get; set; }
        public string Hinhanh { get; set; }
        public string danhmucsanpham { get; set; }
        public string chitietsanpham { get; set; }
        public Nullable<double> Giamthem { get; set; }
        public Nullable<int> phantramkm { get; set; }
        public Nullable<int> Baohanh { get; set; }
        public Nullable<double> Giacu { get; set; }
        public string tinhtrang { get; set; }
    }
}
