//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DientuMenuSitemathang
    {
        public int Id { get; set; }
        public string MenuName { get; set; }
        public string Tag { get; set; }
        public string Level { get; set; }
        public string Logogroup { get; set; }
        public Nullable<int> Ord { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Mota { get; set; }
        public string Url { get; set; }
        public Nullable<int> idThuoctinh { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Index { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public string Title { get; set; }
    }
}
