//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DientuMathang
    {
        public int Id { get; set; }
        public string Seri { get; set; }
        public string Tenhang { get; set; }
        public string Img { get; set; }
        public string ThumImg { get; set; }
        public string Thum_img_img { get; set; }
        public Nullable<int> Idnsx { get; set; }
        public Nullable<double> Giaban { get; set; }
        public Nullable<double> Giamua { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Tinhtrang { get; set; }
        public string Donvi { get; set; }
        public string Baohanh { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
        public Nullable<int> Danhgia { get; set; }
        public Nullable<int> Luotxem { get; set; }
        public Nullable<double> Vat { get; set; }
        public string Lienhe { get; set; }
        public string Forder { get; set; }
        public string Baiviet { get; set; }
        public string Thongso { get; set; }
        public string Mota { get; set; }
        public Nullable<double> Giagiam { get; set; }
        public Nullable<double> Phantramkm { get; set; }
        public string Title { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public string Khuvuc { get; set; }
        public string thuoctinh { get; set; }
        public string khuyenmai { get; set; }
        public string khuyenmai_html { get; set; }
        public Nullable<int> Ord { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> Idmenu { get; set; }
        public Nullable<int> Idthuoctinh { get; set; }
        public string Diemdanhgia { get; set; }
        public Nullable<System.DateTime> Ngayxemganday { get; set; }
        public string Tag { get; set; }
        public string GroupNewsCatTag { get; set; }
        public string Cateprolevel1 { get; set; }
        public string Cateprolevel2 { get; set; }
        public string Cateprolevel3 { get; set; }
        public Nullable<int> Soluongmua { get; set; }
    }
}
