//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DientuThuoctinh
    {
        public int Id { get; set; }
        public string IdTag { get; set; }
        public string Text { get; set; }
        public string Value { get; set; }
        public Nullable<int> Idproduct { get; set; }
        public string TagProduct { get; set; }
        public Nullable<int> Idthuoctinh { get; set; }
        public Nullable<int> Idcapthuoctinh { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Ord { get; set; }
        public string Content { get; set; }
    }
}
