//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DientuInfo
    {
        public int Id { get; set; }
        public string Thuonghieu { get; set; }
        public string Dongmay { get; set; }
        public string Soseri { get; set; }
        public string Hovaten { get; set; }
        public string Sodienthoai { get; set; }
        public string Noidungsuachua { get; set; }
        public string Images1 { get; set; }
        public string Images2 { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<System.DateTime> Ngaygoi { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
