//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Images { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Info { get; set; }
        public string File { get; set; }
        public Nullable<int> Ord { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string Lang { get; set; }
        public string NameEn { get; set; }
        public string infoEn { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
