//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public int IDhd { get; set; }
        public Nullable<int> IDuser { get; set; }
        public string SDT { get; set; }
        public string Hoten { get; set; }
        public string Mail { get; set; }
        public string Diachi { get; set; }
        public string Tinh { get; set; }
        public string Huyen { get; set; }
        public string Xungho { get; set; }
        public string Hinhthucthanhtoan { get; set; }
        public string Goidichvu { get; set; }
        public Nullable<double> Tongtienhang { get; set; }
        public Nullable<double> Thanhtoan { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public string KH { get; set; }
        public string Duyet { get; set; }
        public string Khuyenmai { get; set; }
        public string Hinhthucgiaohang { get; set; }
        public string GhiChuKhac { get; set; }
        public Nullable<int> Tiengiamgia { get; set; }
    }
}
