//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupNewsNewsDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string Image { get; set; }
        public string Content { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> ord { get; set; }
        public string Nguon { get; set; }
        public string Lang { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Images5 { get; set; }
        public string GroupNewsCatTag { get; set; }
        public string Cateprolevel1 { get; set; }
        public string Cateprolevel2 { get; set; }
        public string Cateprolevel3 { get; set; }
        public string NameEn { get; set; }
        public string ContentEn { get; set; }
        public string DetailEn { get; set; }
        public Nullable<System.DateTime> DateView { get; set; }
        public Nullable<int> Luotxem { get; set; }
    }
}
