//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupNewMenuSanPhamDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string Tag { get; set; }
        public string IDthuonghieu { get; set; }
        public string NguonSanPham { get; set; }
        public string Mausac { get; set; }
        public string Kichthuoc { get; set; }
        public string SanphamCungloai { get; set; }
        public string Donvi { get; set; }
        public string Luotdanhgia { get; set; }
        public string Video { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> Active { get; set; }
        public string GroupNewsCatTag { get; set; }
        public string Cateprolevel1 { get; set; }
        public string Cateprolevel2 { get; set; }
        public string Cateprolevel3 { get; set; }
        public string Image { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string Content { get; set; }
        public string ContentEn { get; set; }
        public string Detail { get; set; }
        public string DetailEn { get; set; }
        public string Khuyenmai { get; set; }
        public string KhuyenmaiEn { get; set; }
        public string Baohanh { get; set; }
        public string BaohanhEn { get; set; }
        public string DacDiemNoiBat { get; set; }
        public string DacDiemNoiBatEn { get; set; }
        public string Thongdiep { get; set; }
        public string ThongdiepEn { get; set; }
        public string Seri { get; set; }
        public Nullable<int> Luotxem { get; set; }
        public Nullable<int> Soluongmua { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateView { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Number_Stock { get; set; }
        public Nullable<bool> Vat { get; set; }
        public Nullable<double> Gianhaphang { get; set; }
        public Nullable<double> Giaban { get; set; }
        public Nullable<int> Phantramkhuyenmai { get; set; }
        public Nullable<double> Giabankhuyenmai { get; set; }
        public Nullable<System.DateTime> DateStart_Event { get; set; }
        public Nullable<System.DateTime> DateEnd_Event { get; set; }
        public Nullable<double> Giaban_Event { get; set; }
        public string Content_Event { get; set; }
        public string Content_EventEn { get; set; }
    }
}
