//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Html
    {
        public int id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> Active { get; set; }
        public string Lang { get; set; }
        public string Ten { get; set; }
        public string Html_content { get; set; }
        public string TenEn { get; set; }
        public string Html_contentEn { get; set; }
        public string images { get; set; }
        public Nullable<int> Ord { get; set; }
    }
}
