//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nuocsanxuat
    {
        public int IDNuocsanxuat { get; set; }
        public string TenNuocsanxuat { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Vitri { get; set; }
        public string TenNuocsanxuat_En { get; set; }
    }
}
