//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class quantity_purchased
    {
        public int Id_quantity { get; set; }
        public Nullable<int> Sl_mua { get; set; }
        public Nullable<int> Phan_tram_tang { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
