//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideShow
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Link { get; set; }
        public string Target { get; set; }
        public string Content { get; set; }
        public Nullable<short> Position { get; set; }
        public Nullable<int> Click { get; set; }
        public Nullable<int> Ord { get; set; }
        public bool Active { get; set; }
        public string Lang { get; set; }
        public string Detail { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Tag { get; set; }
        public string NameEn { get; set; }
        public string ContentEn { get; set; }
        public string DetailEn { get; set; }
    }
}
