//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public Nullable<int> Type { get; set; }
        public string Nick { get; set; }
        public Nullable<int> Ord { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> GroupSupportId { get; set; }
        public string Lang { get; set; }
        public Nullable<int> Location { get; set; }
    
        public virtual GroupSupport GroupSupport { get; set; }
    }
}
