//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_ruler
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Province { get; set; }
        public Nullable<int> Tax_pri { get; set; }
        public string Description { get; set; }
        public string File_tax { get; set; }
        public Nullable<int> Ord { get; set; }
        public string NameEn { get; set; }
        public string DescriptionEn { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
