//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuonghieu
    {
        public int IDthuonghieu { get; set; }
        public string Tenthuonghieu { get; set; }
        public string Logo { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Vitri { get; set; }
        public string Lienkettinh { get; set; }
        public string mota { get; set; }
        public string Lang { get; set; }
        public string Tenthuonghieu_En { get; set; }
        public string mota_En { get; set; }
    }
}
