//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Shop_SettingIphone.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tintuc
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
        public string Tomtat { get; set; }
        public string Noidung { get; set; }
        public string Tacgia { get; set; }
        public Nullable<int> Luotxem { get; set; }
        public string Hinhanh { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Ord { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Ngayxemganday { get; set; }
        public string lienkiettinh { get; set; }
        public string NameEn { get; set; }
        public string ContentEn { get; set; }
        public string DetailEn { get; set; }
        public string Nguon { get; set; }
    }
}
